//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 04:27:27 PM CST 
//


package com.litc.model.data.complianceTestReport;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eric.office.data.report package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TestFunction_QNAME = new QName("", "testFunction");
    private final static QName _Desc_QNAME = new QName("", "desc");
    private final static QName _Remark_QNAME = new QName("", "remark");
    private final static QName _ISBN_QNAME = new QName("", "ISBN");
    private final static QName _SoftwareType_QNAME = new QName("", "softwareType");
    private final static QName _DownloadUrl_QNAME = new QName("", "downloadUrl");
    private final static QName _HardwareEnv_QNAME = new QName("", "hardwareEnv");
    private final static QName _Publisher_QNAME = new QName("", "publisher");
    private final static QName _Author_QNAME = new QName("", "author");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _TestResult_QNAME = new QName("", "testResult");
    private final static QName _TestTotalNum_QNAME = new QName("", "testTotalNum");
    private final static QName _SoftwareEnv_QNAME = new QName("", "softwareEnv");
    private final static QName _TestSuccessNum_QNAME = new QName("", "testSuccessNum");
    private final static QName _Year_QNAME = new QName("", "year");
    private final static QName _DevelopmentModel_QNAME = new QName("", "developmentModel");
    private final static QName _EditionNumber_QNAME = new QName("", "editionNumber");
    private final static QName _TestErrorNum_QNAME = new QName("", "testErrorNum");
    private final static QName _SoftwareSize_QNAME = new QName("", "softwareSize");
    private final static QName _SoftwareName_QNAME = new QName("", "softwareName");
    private final static QName _TestCaseValidity_QNAME = new QName("", "testCaseValidity");
    private final static QName _TestCaseType_QNAME = new QName("", "testCaseType");
    private final static QName _Price_QNAME = new QName("", "price");
    private final static QName _TestCaseResult_QNAME = new QName("", "testCaseResult");
    private final static QName _IsOriginal_QNAME = new QName("", "isOriginal");
    private final static QName _Month_QNAME = new QName("", "month");
    private final static QName _Day_QNAME = new QName("", "day");
    private final static QName _TestCaseId_QNAME = new QName("", "testCaseId");
    private final static QName _Language_QNAME = new QName("", "language");
    private final static QName _IsPublish_QNAME = new QName("", "isPublish");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eric.office.data.report
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestCaseInfo }
     * 
     */
    public TestCaseInfo createTestCaseInfo() {
        return new TestCaseInfo();
    }

    /**
     * Create an instance of {@link CaseDetail }
     * 
     */
    public CaseDetail createCaseDetail() {
        return new CaseDetail();
    }

    /**
     * Create an instance of {@link ShouldResult }
     * 
     */
    public ShouldResult createShouldResult() {
        return new ShouldResult();
    }

    /**
     * Create an instance of {@link ActualResult }
     * 
     */
    public ActualResult createActualResult() {
        return new ActualResult();
    }

    /**
     * Create an instance of {@link SoftInfo }
     * 
     */
    public SoftInfo createSoftInfo() {
        return new SoftInfo();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link TestResultInfo }
     * 
     */
    public TestResultInfo createTestResultInfo() {
        return new TestResultInfo();
    }

    /**
     * Create an instance of {@link TestCases }
     * 
     */
    public TestCases createTestCases() {
        return new TestCases();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testFunction")
    public JAXBElement<String> createTestFunction(String value) {
        return new JAXBElement<String>(_TestFunction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "desc")
    public JAXBElement<String> createDesc(String value) {
        return new JAXBElement<String>(_Desc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "remark")
    public JAXBElement<String> createRemark(String value) {
        return new JAXBElement<String>(_Remark_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ISBN")
    public JAXBElement<String> createISBN(String value) {
        return new JAXBElement<String>(_ISBN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "softwareType")
    public JAXBElement<String> createSoftwareType(String value) {
        return new JAXBElement<String>(_SoftwareType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "downloadUrl")
    public JAXBElement<String> createDownloadUrl(String value) {
        return new JAXBElement<String>(_DownloadUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hardwareEnv")
    public JAXBElement<String> createHardwareEnv(String value) {
        return new JAXBElement<String>(_HardwareEnv_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publisher")
    public JAXBElement<String> createPublisher(String value) {
        return new JAXBElement<String>(_Publisher_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "author")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testResult")
    public JAXBElement<String> createTestResult(String value) {
        return new JAXBElement<String>(_TestResult_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testTotalNum")
    public JAXBElement<Byte> createTestTotalNum(Byte value) {
        return new JAXBElement<Byte>(_TestTotalNum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "softwareEnv")
    public JAXBElement<String> createSoftwareEnv(String value) {
        return new JAXBElement<String>(_SoftwareEnv_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testSuccessNum")
    public JAXBElement<Byte> createTestSuccessNum(Byte value) {
        return new JAXBElement<Byte>(_TestSuccessNum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "year")
    public JAXBElement<Short> createYear(Short value) {
        return new JAXBElement<Short>(_Year_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "developmentModel")
    public JAXBElement<String> createDevelopmentModel(String value) {
        return new JAXBElement<String>(_DevelopmentModel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "editionNumber")
    public JAXBElement<String> createEditionNumber(String value) {
        return new JAXBElement<String>(_EditionNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testErrorNum")
    public JAXBElement<Byte> createTestErrorNum(Byte value) {
        return new JAXBElement<Byte>(_TestErrorNum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "softwareSize")
    public JAXBElement<String> createSoftwareSize(String value) {
        return new JAXBElement<String>(_SoftwareSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "softwareName")
    public JAXBElement<String> createSoftwareName(String value) {
        return new JAXBElement<String>(_SoftwareName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testCaseValidity")
    public JAXBElement<String> createTestCaseValidity(String value) {
        return new JAXBElement<String>(_TestCaseValidity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testCaseType")
    public JAXBElement<String> createTestCaseType(String value) {
        return new JAXBElement<String>(_TestCaseType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "price")
    public JAXBElement<String> createPrice(String value) {
        return new JAXBElement<String>(_Price_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testCaseResult")
    public JAXBElement<String> createTestCaseResult(String value) {
        return new JAXBElement<String>(_TestCaseResult_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isOriginal")
    public JAXBElement<String> createIsOriginal(String value) {
        return new JAXBElement<String>(_IsOriginal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "month")
    public JAXBElement<Byte> createMonth(Byte value) {
        return new JAXBElement<Byte>(_Month_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "day")
    public JAXBElement<Byte> createDay(Byte value) {
        return new JAXBElement<Byte>(_Day_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testCaseId")
    public JAXBElement<String> createTestCaseId(String value) {
        return new JAXBElement<String>(_TestCaseId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "language")
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isPublish")
    public JAXBElement<String> createIsPublish(String value) {
        return new JAXBElement<String>(_IsPublish_QNAME, String.class, null, value);
    }

}
