//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 04:27:27 PM CST 
//


package com.litc.model.data.complianceTestReport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}softInfo"/>
 *         &lt;element ref="{}testResultInfo"/>
 *         &lt;element ref="{}testCases"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "softInfo",
    "testResultInfo",
    "testCases"
})
@XmlRootElement(name = "report")
public class Report {

    @XmlElement(required = true)
    protected SoftInfo softInfo;
    @XmlElement(required = true)
    protected TestResultInfo testResultInfo;
    @XmlElement(required = true)
    protected TestCases testCases;

    /**
     * Gets the value of the softInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SoftInfo }
     *     
     */
    public SoftInfo getSoftInfo() {
        return softInfo;
    }

    /**
     * Sets the value of the softInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftInfo }
     *     
     */
    public void setSoftInfo(SoftInfo value) {
        this.softInfo = value;
    }

    /**
     * Gets the value of the testResultInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TestResultInfo }
     *     
     */
    public TestResultInfo getTestResultInfo() {
        return testResultInfo;
    }

    /**
     * Sets the value of the testResultInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestResultInfo }
     *     
     */
    public void setTestResultInfo(TestResultInfo value) {
        this.testResultInfo = value;
    }

    /**
     * Gets the value of the testCases property.
     * 
     * @return
     *     possible object is
     *     {@link TestCases }
     *     
     */
    public TestCases getTestCases() {
        return testCases;
    }

    /**
     * Sets the value of the testCases property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestCases }
     *     
     */
    public void setTestCases(TestCases value) {
        this.testCases = value;
    }

}
