//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 04:27:27 PM CST 
//


package com.litc.model.data.complianceTestReport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}softwareName"/>
 *         &lt;element ref="{}softwareType"/>
 *         &lt;element ref="{}isOriginal"/>
 *         &lt;element ref="{}developmentModel"/>
 *         &lt;element ref="{}isPublish"/>
 *         &lt;element ref="{}softwareSize"/>
 *         &lt;element ref="{}hardwareEnv"/>
 *         &lt;element ref="{}softwareEnv"/>
 *         &lt;element ref="{}language"/>
 *         &lt;element ref="{}desc"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "softwareName",
    "softwareType",
    "isOriginal",
    "developmentModel",
    "isPublish",
    "softwareSize",
    "hardwareEnv",
    "softwareEnv",
    "language",
    "desc"
})
@XmlRootElement(name = "softInfo")
public class SoftInfo {

    @XmlElement(required = true)
    protected String softwareName;
    @XmlElement(required = true)
    protected String softwareType;
    @XmlElement(required = true)
    protected String isOriginal;
    @XmlElement(required = true)
    protected String developmentModel;
    @XmlElement(required = true)
    protected String isPublish;
    @XmlElement(required = true)
    protected String softwareSize;
    @XmlElement(required = true)
    protected String hardwareEnv;
    @XmlElement(required = true)
    protected String softwareEnv;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(required = true)
    protected String desc;

    /**
     * Gets the value of the softwareName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareName() {
        return softwareName;
    }

    /**
     * Sets the value of the softwareName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareName(String value) {
        this.softwareName = value;
    }

    /**
     * Gets the value of the softwareType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareType() {
        return softwareType;
    }

    /**
     * Sets the value of the softwareType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareType(String value) {
        this.softwareType = value;
    }

    /**
     * Gets the value of the isOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsOriginal() {
        return isOriginal;
    }

    /**
     * Sets the value of the isOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsOriginal(String value) {
        this.isOriginal = value;
    }

    /**
     * Gets the value of the developmentModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDevelopmentModel() {
        return developmentModel;
    }

    /**
     * Sets the value of the developmentModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDevelopmentModel(String value) {
        this.developmentModel = value;
    }

    /**
     * Gets the value of the isPublish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPublish() {
        return isPublish;
    }

    /**
     * Sets the value of the isPublish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPublish(String value) {
        this.isPublish = value;
    }

    /**
     * Gets the value of the softwareSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareSize() {
        return softwareSize;
    }

    /**
     * Sets the value of the softwareSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareSize(String value) {
        this.softwareSize = value;
    }

    /**
     * Gets the value of the hardwareEnv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHardwareEnv() {
        return hardwareEnv;
    }

    /**
     * Sets the value of the hardwareEnv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHardwareEnv(String value) {
        this.hardwareEnv = value;
    }

    /**
     * Gets the value of the softwareEnv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareEnv() {
        return softwareEnv;
    }

    /**
     * Sets the value of the softwareEnv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareEnv(String value) {
        this.softwareEnv = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

}
