//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 04:27:27 PM CST 
//


package com.litc.model.data.complianceTestReport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}year"/>
 *         &lt;element ref="{}month"/>
 *         &lt;element ref="{}day"/>
 *         &lt;element ref="{}testResult"/>
 *         &lt;element ref="{}testTotalNum"/>
 *         &lt;element ref="{}testSuccessNum"/>
 *         &lt;element ref="{}testErrorNum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "year",
    "month",
    "day",
    "testResult",
    "testTotalNum",
    "testSuccessNum",
    "testErrorNum"
})
@XmlRootElement(name = "testResultInfo")
public class TestResultInfo {

    protected short year;
    protected byte month;
    protected byte day;
    @XmlElement(required = true)
    protected String testResult;
    protected byte testTotalNum;
    protected byte testSuccessNum;
    protected byte testErrorNum;

    /**
     * Gets the value of the year property.
     * 
     */
    public short getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     */
    public void setYear(short value) {
        this.year = value;
    }

    /**
     * Gets the value of the month property.
     * 
     */
    public byte getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     */
    public void setMonth(byte value) {
        this.month = value;
    }

    /**
     * Gets the value of the day property.
     * 
     */
    public byte getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     */
    public void setDay(byte value) {
        this.day = value;
    }

    /**
     * Gets the value of the testResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * Sets the value of the testResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestResult(String value) {
        this.testResult = value;
    }

    /**
     * Gets the value of the testTotalNum property.
     * 
     */
    public byte getTestTotalNum() {
        return testTotalNum;
    }

    /**
     * Sets the value of the testTotalNum property.
     * 
     */
    public void setTestTotalNum(byte value) {
        this.testTotalNum = value;
    }

    /**
     * Gets the value of the testSuccessNum property.
     * 
     */
    public byte getTestSuccessNum() {
        return testSuccessNum;
    }

    /**
     * Sets the value of the testSuccessNum property.
     * 
     */
    public void setTestSuccessNum(byte value) {
        this.testSuccessNum = value;
    }

    /**
     * Gets the value of the testErrorNum property.
     * 
     */
    public byte getTestErrorNum() {
        return testErrorNum;
    }

    /**
     * Sets the value of the testErrorNum property.
     * 
     */
    public void setTestErrorNum(byte value) {
        this.testErrorNum = value;
    }

}
