//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 04:27:27 PM CST 
//


package com.litc.model.data.complianceTestReport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}testCaseId"/>
 *         &lt;element ref="{}testCaseType"/>
 *         &lt;element ref="{}testCaseResult"/>
 *         &lt;element ref="{}remark"/>
 *         &lt;element ref="{}downloadUrl"/>
 *         &lt;choice>
 *           &lt;element ref="{}caseDetail" maxOccurs="unbounded"/>
 *           &lt;sequence>
 *             &lt;element ref="{}shouldResult"/>
 *             &lt;element ref="{}actualResult"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testCaseId",
    "testCaseType",
    "testCaseResult",
    "remark",
    "downloadUrl",
    "caseDetail",
    "shouldResult",
    "actualResult"
})
@XmlRootElement(name = "testCaseInfo")
public class TestCaseInfo {

    @XmlElement(required = true)
    protected String testCaseId;
    @XmlElement(required = true)
    protected String testCaseType;
    @XmlElement(required = true)
    protected String testCaseResult;
    @XmlElement(required = true)
    protected String remark;
    @XmlElement(required = true)
    protected String downloadUrl;
    protected List<CaseDetail> caseDetail;
    protected ShouldResult shouldResult;
    protected ActualResult actualResult;

    /**
     * Gets the value of the testCaseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestCaseId() {
        return testCaseId;
    }

    /**
     * Sets the value of the testCaseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestCaseId(String value) {
        this.testCaseId = value;
    }

    /**
     * Gets the value of the testCaseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestCaseType() {
        return testCaseType;
    }

    /**
     * Sets the value of the testCaseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestCaseType(String value) {
        this.testCaseType = value;
    }

    /**
     * Gets the value of the testCaseResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestCaseResult() {
        return testCaseResult;
    }

    /**
     * Sets the value of the testCaseResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestCaseResult(String value) {
        this.testCaseResult = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the downloadUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * Sets the value of the downloadUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDownloadUrl(String value) {
        this.downloadUrl = value;
    }

    /**
     * Gets the value of the caseDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the caseDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaseDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaseDetail }
     * 
     * 
     */
    public List<CaseDetail> getCaseDetail() {
        if (caseDetail == null) {
            caseDetail = new ArrayList<CaseDetail>();
        }
        return this.caseDetail;
    }

    /**
     * Gets the value of the shouldResult property.
     * 
     * @return
     *     possible object is
     *     {@link ShouldResult }
     *     
     */
    public ShouldResult getShouldResult() {
        return shouldResult;
    }

    /**
     * Sets the value of the shouldResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShouldResult }
     *     
     */
    public void setShouldResult(ShouldResult value) {
        this.shouldResult = value;
    }

    /**
     * Gets the value of the actualResult property.
     * 
     * @return
     *     possible object is
     *     {@link ActualResult }
     *     
     */
    public ActualResult getActualResult() {
        return actualResult;
    }

    /**
     * Sets the value of the actualResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualResult }
     *     
     */
    public void setActualResult(ActualResult value) {
        this.actualResult = value;
    }

}
